### ISSUE TITLE
Cadastro precisa retornar ID

### ISSUE THREAD

**Issue by mateustranquilino** [issilva5/projeto-plp-2020_3#11]
Quando uma nova entidade (UBS, Médico ou Paciente) é cadastrada o ID não é pedido para o usuário, é criado automaticamente. Entretanto o mesmo ID é necessário para a entidade cadastrada fazer Login, assim torna-se necessário uma mensagem após o cadastro informando o ID gerado que identificará essa identidade no sistema para que o usuário fique ciente de qual o seu ID para efetuar o login.

**Comment by issilva5** [comment]
É eu tinha notado que tava sem isso. Mas é só imprimir o ID quando for gerado. Farei isso nas correções de amanhã.
